apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Prometheus服务地址（容器名+端口）
    isDefault: true  # 设置为默认数据源
    editable: true
    jsonData:
      timeInterval: "15s"  # 数据查询间隔
    version: 1
